components/info_center/config/routes.rb
InfoCenter::Engine.routes.draw do
    resources :deficits
end

components/info_center/app/models/info_center/deficit.rb
module InfoCenter
  class Deficit < ActiveRecord::Base

    enum benefit: ["Bolsa Família","Auxílio-aluguel","BPC","Auxílio-reclusão"]
    enum family_income: ["0 a 3","3 a 6","6 a 10","10 +"]
    enum property_type: ["Urbano","Rural"]
    
  end
end

components/info_center/app/controllers/info_center/application_controller.rb
require_dependency 'authenticate/staff_service'
require_dependency 'authenticate/staff_helper'
module InfoCenter
  class ApplicationController < ActionController::Base
    layout 'patternfly/mobile-less-application'

    include Pundit
    include Authenticate::StaffService
    helper  Authenticate::StaffHelper
    helper  ::NavigationHelper

    before_action :authenticate_staff?

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  end
end

components/info_center/app/controllers/info_center/deficits_controller.rb
require_dependency 'info_center/application_controller'

module InfoCenter
  class DeficitsController < ApplicationController
    before_action :set_deficit, only: [:show, :edit, :update, :destroy]

    def index
      @deficits = Deficit.all
    end

    def new
      @deficit = Deficit.new
    end

    def edit
    end
    def create
      @deficit = Deficit.new(deficit_params)
      if @deficit.save
        redirect_to action: 'index'
      else
        render :new
      end
    end


    def update
      if @deficit.update(deficit_params)
        redirect_to action: 'index'
      else
        render :edit
      end
    end

    def destroy
      @deficit.destroy
      redirect_to deficits_url, notice: 'Post was successfully destroyed.'
    end

    private
      def set_deficit
        @deficit = InfoCenter::Deficit.find(params[:id])
      end

      def deficit_params
        params.require(:deficit).permit( :name, :property_type, :benefit,:family_income,:cpf,:phone,:address,:lot_houses,:lot_people,:water,:light,:sidewalk,:sewer,:asphalt,:bathroom,:total_bathroom,:kitchen,:roof,:slab,:contract,:document,:people_living,:wall,:room,:sleep_local,:rent,:rent_total,:buy_lot)
      end
  end
end

components/info_center/app/helpers/info_center/application_helper.rb
module InfoCenter
  module ApplicationHelper
  end
end

components/info_center/app/views/info_center/deficits/_form.html.haml
= simple_form_for(@deficit) do |f|
  .card-body.card-padding
    .row
      .col-md-12
        = f.label "Nome"
        = f.input :name,label: false,input_html: { placeholder: 'Digite um nome'}
      .col-md-12
        = f.label "CPF"
        = f.input :cpf,label: false,input_html: { placeholder: 'Digite um cpf'}
      .col-md-12
        = f.label "Telefone"
        = f.input :phone,label: false,input_html: { placeholder: 'Digite apenas números'}
      .col-md-12
        = f.label "Endereço"
        = f.input :address,label: false,input_html: { placeholder: 'Digite um endereço válido'}
      .col-md-12
        = f.label "Qual tipo do seu imóvel"
        = f.input :property_type, label: false, include_blank: false
      .col-md-12
        = f.label "Recebe beneficio do governo? qual?"
        = f.input :benefit, label: false
      .col-md-12
        = f.label "Quantas casas tem em seu lote?"
        = f.input :lot_houses, label: false, include_blank: false, input_html: {placeholder: 'Apenas números'}
      .col-md-12
        = f.label "Quem mora no Lote?"
        = f.input :lot_people, label: false, input_html: { placeholder: 'Ex: Maria Pereira - CPF: 00882853161 ',id: 'lot_people', rows: 5, cols: 80}
      .col-md-12
        = f.label "Onde você mora tem:"
        = f.input :water, inline_label: 'Água'
        = f.input :light, inline_label: 'Luz'
        = f.input :asphalt, inline_label: 'Asfalto'
        = f.input :sewer, inline_label: 'Esgoto'
        = f.input :sidewalk, inline_label: 'Calçada'
      .col-md-12
        = f.label "Sua casa tem cozinha?"
        = f.input :kitchen, as: :select, label: false, include_blank: false
      .col-md-12
        = f.label "Sua casa tem laje?"
        = f.input :slab, as: :select, label: false, include_blank: false
      .col-md-12
        = f.label "Você tem a escritura do seu lote?"
        = f.input :contract, as: :select, label: false, include_blank: false
      .col-md-12
        = f.label "Quais documentos do lote você possui?"
        = f.input :document, label: false, include_blank: false, input_html: { placeholder: 'Descreva...', id: 'roof', rows: 5, cols: 80}
      .col-md-12
        = f.label "Qual a situação do telhado da sua casa?"
        = f.input :roof, label: false, input_html: { placeholder: 'Descreva...', id: 'roof', rows: 5, cols: 80}
      .col-md-12
        = f.label "Existem paredes entre quartos, coziha, sala, etc?"
        = f.input :wall, as: :select, label: false, include_blank: false
      .col-md-12
        = f.label "Quantas pessoas moram em sua casa?"
        = f.input :people_living,  label: false, include_blank: false
        .col-md-12
        = f.label "Quantos quartos tem?"
        = f.input :room,  label: false, include_blank: false
      .col-md-12
        = f.label "Quem dorme onde?"
        = f.input :sleep_local, label: false, input_html: { placeholder: 'Descreva...', id: 'roof', rows: 5, cols: 80}
      .col-md-12
        = f.label "Qual sua renda familiar? (Salarios mínimos)"
        = f.input :family_income,label: false, include_blank: false
      .col-md-12
        = f.label "Você paga aluguel?"
        = f.input :rent, as: :select, label: false, include_blank: false
      .col-md-12
        = f.label "Se sim, quanto paga?"
        = f.input :rent_total, label: false, include_blank: false
      .col-md-12
        = f.label "Se a CODHAB te vendesse um lote você gostaria de comprar ?"
        = f.input :buy_lot, as: :select, label: false, include_blank: false
    .row
      .col-md-12
        = f.button :submit, class: 'btn btn-success', data: {disable_with: t(:disable_with)}
        = link_to t(:button_back) ,deficits_path , class: 'btn btn-default'

components/info_center/app/views/info_center/deficits/edit.html.haml
.panel.panel-default
  .panel-heading
    %h4.panel-title
      Editar
      %span.pull-right
        = link_to "Voltar para listagem", deficits_path
  .panel-body
    .row
      .col-md-12
        = render 'form'

components/info_center/app/views/info_center/deficits/index.html.haml
.panel.panel-default
  .panel-heading
    %h4.panel-title
      Cadastro de Déficit
      = link_to 'Novo', new_deficit_path,  data: { no_turbolink: true }, class: 'pull-right'
  .panel-body

    %br/
    .row
      .col-md-12
        %table.table.table-striped.table-bordered
          %thead
            %tr
              %th Nome
              %th CPF
              %th Ações

          %tbody
            - @deficits.each do |deficit|
              %tr
                %td= deficit.name
                %td= deficit.cpf
                %td.col-md-2
                  = link_to '', edit_deficit_path(deficit), class: 'glyphicon glyphicon-pencil  btn btn-primary btn-xs', data: {turbolinks: false}
                  = link_to '', deficit, class: 'glyphicon glyphicon-remove  btn btn-danger btn-xs', :method => :delete, :data => { :confirm => 'Are you sure?' }

components/info_center/app/views/info_center/deficits/new.html.haml
.panel.panel-default
  .panel-heading
    %h4.panel-title
      Novo
      %span.pull-right
        = link_to "Voltar para listagem", deficits_path
  .panel-body
    .row
      .col-md-12
        = render 'form'