components/archive/config/routes.rb
Archive::Engine.routes.draw do
  resources :files
  resources :images 

  post 'upload_file', to: 'images#upload_file', as: 'upload_file'
end

components/archive/app/models/archive/file.rb
module Archive
  class File < ActiveRecord::Base
    belongs_to :staff, class_name: "Person::Staff"

    default_scope -> { where(deleted: false)}
    
    validates :original_name, presence: true, uniqueness: true

    validates :file_path, presence: true
    validates :file_path, file_size: { less_than_or_equal_to: 100.megabytes.to_i,
                                       message: "Arquivo não pode exceder 100 MB" }
   
    mount_uploader :file_path, Archive::FileUploader 
    
  end
end

components/archive/app/models/archive/image.rb
module Archive
  class Image < ActiveRecord::Base
    belongs_to :staff, class_name: "Person::Staff"

#    validates :original_name, presence: true, uniqueness: true

    
    validates :file_path, presence: true
    validates :file_path, file_size: { less_than_or_equal_to: 10.megabytes.to_i }
    validates :file_path, file_content_type: { allow: ['image/jpeg', 'image/png'],
                                              message: 'Somente arquivos .jpg ou .png' }

    mount_uploader :file_path, Archive::ImageUploader 
  end
end

components/archive/app/controllers/archive/application_controller.rb
require_dependency 'authenticate/staff_service'
require_dependency 'authenticate/staff_helper'

module Archive
  class ApplicationController < ActionController::Base
    layout 'patternfly/application'
    
    include Pundit
    include Authenticate::StaffService
    helper  Authenticate::StaffHelper
    helper  ::NavigationHelper
    
    before_action :authenticate_staff?

  end
end

components/archive/app/controllers/archive/files_controller.rb
require_dependency 'archive/application_controller'

module Archive
  class FilesController < ApplicationController
  
    def index
      @files = Archive::File.all.order('id DESC')
    end

    def new
      @file = Archive::File.new
    end

    def create
      @file = Archive::File.new(set_params)
      @file.staff_id  = current_user.id

      if @file.save 
        flash[:success] = t :success
        redirect_to action: :index
      else
        render action: :new
      end
    end

    def destroy
    end

    private

    def set_params
      params.require(:file).permit(:original_name, :hash_name, :file_path, :staff_id, :sector_id)
    end

  end
end

components/archive/app/controllers/archive/images_controller.rb
require_dependency 'archive/application_controller'

module Archive
  class ImagesController < ApplicationController
  
    def index
      @images = Archive::Image.all.order('id DESC')
    end

    def new
      @image = Archive::Image.new
    end

    def create
      @image = Archive::Image.new(set_params)
      @image.staff_id  = current_user.id

      if @image.save 
        flash[:success] = t :success
        redirect_to action: :index
      else
        render action: :new
      end
    end

    def upload_file
      @image = Archive::Image.new
      @image.file_path = params[:file]
      @image.staff_id  = current_user.id

      if @image.save
         render json: {
            image: {
              url: @image.file_path.url
            }
          }, content_type: "text/html"
      else
        render json: false
      end 
  
  end

    def destroy
    end

    private

    def set_params
      params.require(:image).permit(:original_name, :hash_name, :file_path, :staff_id, :sector_id)
    end

  end
end

components/archive/app/views/archive/files/_form.html.haml
= simple_form_for @file do |f|
  .row
    .col-md-6
      = f.input :original_name
  .row
    .col-md-8
      = f.input :description
  %hr/
  .row
    .col-md-8
      = f.input :file_path, as: :file
  %hr/
  .row
    .col-md-12
      = f.submit "Salvar arquivo", class: 'btn btn-success', data: { disable_with: t(:disable_with)}
      = link_to "Voltar para listagem", files_path, class: 'btn btn-dark', data: { disable_with: t(:disable_with)}

components/archive/app/views/archive/files/_index.html.haml
.modal-header
  %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
    %span{"aria-hidden" => "true"} ×
  %h3 
    %strong Últimos 20 documentos 
.modal-body
  .table-responsive{:style => "overflow: hidden; outline: none;", :tabindex => "3"}
    %table#data-table-command.table.table-striped.table-bordered.table-condensed
      %thead
        %tr
          %th Cod.
          %th Nome
          %th Link
      %tbody
        - @files.limit(20).each do |file| 
          %tr
            %td.col-md-1= file.id
            %td.col-md-4= file.original_name.downcase
            %td= "http://www.codhab.df.gov.br#{file.file_path.to_s}"
          

components/archive/app/views/archive/files/index.html.haml
.panel.panel-default
  .panel-heading
    %h4.panel-title
      Documentos 
      = link_to "novo documento", new_file_path, class: 'pull-right'
  .panel-body
    .table-responsive{:style => "overflow: hidden; outline: none;", :tabindex => "3"}
      %table#data-table-command.table.table-striped.table-bordered
        %thead
          %tr
            %th Cod.
            %th Nome
            %th Link
            %th Data de Criação
            %th Usuário
            %th Ações

        %tbody
          - @files.each do |file| 
            %tr
              %td.col-md-1= file.id
              %td.col-md-2= file.original_name.downcase
              %td= link_to "http://www.codhab.df.gov.br#{file.file_path.to_s}", file.file_path.to_s, target: '_blank'
              %td.col-md-3= file.created_at.strftime('%d/%m/%Y')
              %td= file.staff.code
              %td
                = link_to "", file_path(file), method: :delete, data: { confirm: t(:confirm_delete)}, class: 'btn btn-danger btn-xs glyphicon glyphicon-remove'

components/archive/app/views/archive/files/index.js.haml
$('#modal-size').addClass('modal-lg')
$('#modal .modal-content').html("#{escape_javascript(render 'index')}")
$('#modal').modal('show')

components/archive/app/views/archive/files/new.html.haml
.page-content
  .panel
    .panel-heading
      .panel-title
        %h4 Novo Documento
    .panel-body
      .row
        .col-md-12
          = render 'form'