components/habitation_attendance/config/routes.rb
HabitationAttendance::Engine.routes.draw do
  
  namespace :enabled do 
    resources :attendances
    resources :dashboard
    resources :cadastres do 
      get 'checklist'
    end

    resources :dependents
    resources :checklists do 
      get 'enable'
      get 'disable'

      get 'auth'
      get 'unauth'
    end
    resources :finish
  end

  namespace :convoke do 
    resources :dashboard
    resources :attendances
    resources :cadastre_mirrors do 
      resources :dependent_mirrors
      resources :checklists do 
        get 'check'
        get 'uncheck'
      end
    end
  end  
end

components/habitation_attendance/app/models/habitation_attendance/convoke/attendance.rb
module HabitationAttendance
  module Convoke
    class Attendance < Candidate::CadastreAttendance
    
      def initialize_attendance!(cpf, staff_id)
        cadastre = Candidate::Cadastre.habitation.situation(3).find_by_cpf(cpf.unformat_cpf) rescue nil
        return false if cadastre.nil? || staff_id.nil?

        mirror = cadastre.cadastre_mirrors.new
        mirror.set_clone(cadastre.attributes)
        mirror.save
        mirror.set_clone_dependent(cadastre.dependents)
        
        attendance = Candidate::CadastreAttendance.new
        attendance.cadastre_id        = cadastre.id
        attendance.cadastre_mirror_id = mirror.id
        attendance.staff_id           = staff_id
        attendance.attendance_type    = 1
        attendance.situation          = 0
        attendance.save

        status = attendance.cadastre_attendance_statuses.new

        status.attendance_status_id = 4
        status.staff_id             = staff_id
        status.mirror_id            = mirror.id
        status.save
      end

    end
  end
end

components/habitation_attendance/app/controllers/habitation_attendance/convoke/attendances_controller.rb
require_dependency 'habitation_attendance/application_controller'

module HabitationAttendance
  module Convoke
    class AttendancesController < ApplicationController
    
      def new     
        @attendance = Convoke::Attendance.new

        if @attendance.initialize_attendance!(params[:cpf], current_user.id)
          flash[:success] =  "Atendimento iniciado com sucesso!"
        else
          flash[:danger]  =  "Não foi possível iniciar o atendimento! Verifique se existe atendimentos em aberto."
        end
        
        redirect_to convoke_dashboard_index_path(cpf: params[:cpf]) 
      end

      def destroy
      end

    end
  end
end

components/habitation_attendance/app/controllers/habitation_attendance/convoke/cadastre_mirrors_controller.rb
require_dependency 'habitation_attendance/application_controller'

module HabitationAttendance
  module Convoke
    class CadastreMirrorsController < ApplicationController
    
      def edit
        @cadastre_mirror = Candidate::CadastreMirror.find(params[:id])
      end

      def update
        @cadastre_mirror = Candidate::CadastreMirror.find(params[:id])
        if @cadastre_mirror.update(set_params)
          flash[:success] = t :success
          redirect_to action: :edit
        else
          render action: :edit
        end
      end

      private

      def set_params
        params.require(:cadastre_mirror).permit(:born, :gender, :civil_state_id, :arrival_df,
                                               :income, :special_condition_id, :adapted_property,
                                               :cid, :nis)
      end
    end
  end
end

components/habitation_attendance/app/controllers/habitation_attendance/convoke/checklists_controller.rb
require_dependency 'habitation_attendance/application_controller'

module HabitationAttendance
  module Convoke
    class ChecklistsController < ApplicationController
      before_action :set_checklist_type
      before_action :set_cadastre_mirror

      def index
      end
      
      def new     
      end

      private

      def set_checklist_type
        @type = Candidate::ChecklistType.find_by_name('morar_bem')
      end

      def set_cadastre_mirror
        @cadastre_mirror = Candidate::CadastreMirror.find(params[:cadastre_mirror_id])
      end
    end
  end
end

components/habitation_attendance/app/controllers/habitation_attendance/convoke/dashboard_controller.rb
require_dependency 'habitation_attendance/application_controller'

module HabitationAttendance
  module Convoke
    class DashboardController < ApplicationController
    
      def index
        @candidate = Candidate::Cadastre.habitation.situation(3).find_by_cpf(params[:cpf].unformat_cpf) rescue nil
      end

    end
  end
end

components/habitation_attendance/app/controllers/habitation_attendance/convoke/dependent_mirrors_controller.rb
require_dependency 'habitation_attendance/application_controller'

module HabitationAttendance
  module Convoke
    class DependentMirrorsController < ApplicationController
     
      before_action :set_mirror
      before_action :set_dependent, only: [:edit, :update, :destroy]

      def index
      end

      def new
        @dependent_mirror = @cadastre_mirror.dependent_mirrors.new
      end

      def create
        @dependent_mirror = @cadastre_mirror.dependent_mirrors.new(set_params)
        @dependent_mirror.save
      end

      def edit
      end

      def update
        @dependent_mirror.update(set_params)
      end

      def destroy
        @dependent_mirror.destroy
      end

      private

      def set_dependent
        @dependent_mirror = @cadastre_mirror.dependent_mirrors.find(params[:id])
      end

      def set_mirror
        @cadastre_mirror = Candidate::CadastreMirror.find(params[:cadastre_mirror_id])
      end

      def set_params
        params.require(:dependent_mirror).permit(:name)
      end
    end
  end
end

components/habitation_attendance/app/views/habitation_attendance/convoke/dependent_mirrors/_index.html.haml
- @cadastre_mirror.dependent_mirrors.each do |mirror|
  %tr
    %td= mirror.name
    %td= mirror.cpf
    %td= mirror.gender
    %td= mirror.born.strftime("%d/%m/%Y") if mirror.born.present?
    %td= mirror.special_condition.name if mirror.special_condition.present?
    %td= mirror.co_acquirer ? mirror.percentage : 'Não'
    %td= number_to_currency mirror.income
    %td
      = link_to "", edit_convoke_cadastre_mirror_dependent_mirror_path(cadastre_mirror_id: @cadastre_mirror.id, id: mirror.id), remote: true, class: 'btn btn-primary btn-xs glyphicon glyphicon-pencil' 
      = link_to "", convoke_cadastre_mirror_dependent_mirror_path(cadastre_mirror_id: @cadastre_mirror.id, id: mirror.id),method: :delete, remote: true, data: { confirm: t(:confirm)}, class: 'btn btn-danger btn-xs glyphicon glyphicon-remove'

components/habitation_attendance/app/views/habitation_attendance/convoke/dependent_mirrors/index.html.haml
.panel.panel-default
  .panel-heading
    %h4.panel-title
      Atendimento - Atualização de dependentes
  .panel-body
    .row
      .col-md-12
        = link_to "+ Adicionar dependente",new_convoke_cadastre_mirror_dependent_mirror_path(cadastre_mirror_id: @cadastre_mirror.id), remote: true, class: 'btn btn-success'
    %br/
    %br/
    .row
      .col-md-12
        %table.table.tabel-hover.table-striped.table-bordered
          %thead
            %tr
              %th Nome
              %th CPF
              %th Sexo
              %th Nascimento
              %th Condição Especial
              %th Co-adquirente
              %th Renda R$
              %th Ação
          %tbody.index-dependent
            = render 'index'

    %hr/
    .row
      .col-md-12
        = link_to "Voltar para atualização de cadastral", edit_convoke_cadastre_mirror_path(id: @cadastre_mirror.id), class: 'btn btn-default btn-lg pull-left'
        = link_to "Avançar para preenchimento de checklist", convoke_cadastre_mirror_checklists_path(cadastre_mirror_id: @cadastre_mirror.id), class: 'btn btn-primary btn-lg pull-right'