components/habitation_portal/config/routes.rb
HabitationPortal::Engine.routes.draw do
  get 'cadastre', path: 'meu-cadastro', to: 'cadastres#show'

  get   'authenticate', path: 'verificacao', to: 'authenticate#new', as: 'new_authenticate'
  post  'authenticate', path: 'verificacao', to: 'authenticate#create', as: 'authenticate'

  resources :lists, path: 'listas'
  resources :candidates, path: 'candidato' do
    get 'pontuation'
    get 'position'
    get 'indication'

    collection do
      get 'update_positions', path: 'lista_alteracao'
      get 'programs', path: 'programs'
      get 'enterprise_cadastre_situation', path: 'situacao_empresa'
    end

    get 'detail', path: 'detalhe'
  end

  get   '/pesquisa-cpf',  to: 'candidates#find_candidate', as: 'find_candidate'
  post  '/pesquisa-cpf',  to: 'candidates#show_candidate', as: 'show_candidate'
end

components/habitation_portal/app/models/habitation_portal/authenticate.rb
module HabitationPortal
  class Authenticate
    include ActiveModel::Model

    attr_accessor :cpf, :password, :born, :email, :id

    validates :cpf, cpf: true, presence: true
    validates :password, presence: true

  end
end

components/habitation_portal/app/models/habitation_portal/find.rb
require_dependency 'candidate/cadastre'

module HabitationPortal
  class Find
    include ActiveModel::Model

    attr_accessor :cpf, :id

    validates :cpf, cpf: true, presence: true
    validate  :cpf_exists?

    private

    def cpf_exists?
      cpf = ::Candidate::Cadastre.habitation.where(cpf: self.cpf)

      if cpf.present?
        self.id = cpf.first.id
      else
        errors.add(:cpf, "CPF não encontrado")
      end

    end
  end
end

components/habitation_portal/app/controllers/habitation_portal/application_controller.rb
module HabitationPortal
  class ApplicationController < ActionController::Base
    layout 'shared/portal'

    helper 'portal/application'
  end
end

components/habitation_portal/app/controllers/habitation_portal/candidates_controller.rb
require_dependency 'habitation_portal/application_controller'

module HabitationPortal
  class CandidatesController < ApplicationController
    before_action :set_headers, only: [:detail]
    before_action :add_cors_headers

    def find_candidate
      @candidate = Find.new
    end

    def show_candidate
      @candidate = Find.new(set_params_find)

      if @candidate.valid?
        redirect_to action: 'show', id: @candidate.id
      else
        render action: 'find_candidate'
      end
    end

    def show


      respond_to do |format|
        format.html{
        @candidate =  Candidate::Cadastre.find(params[:id])
        }
        format.json {
          @candidate = Candidate::Cadastre.find_by_cpf(params[:id])
          render json: @candidate
        }
      end
    end

    def pontuation
      @candidate = Candidate::Cadastre.by_cpf(params[:candidate_id]).first
      render json: @candidate.pontuations.order('code DESC')
    end

    def position
      @candidate = Candidate::Cadastre.by_cpf(params[:candidate_id]).first

      @json = Array.new

      if @candidate.list.present?
        @candidate.list.each do |list|
          @json << {
            situation: @candidate.current_situation_name,
            situation_status: @candidate.current_situation_status,
            zone: list[1][0],
            position: list[2],
            list: list[0],
            pontuation: @candidate.pontuations.present? ? @candidate.pontuations.last.total : nil
          }
        end
      end

      render json: @json

    end

    def indication

      @candidate = Candidate::Cadastre.by_cpf(params[:candidate_id]).first

      @json = Array.new

      @candidate.enterprise_cadastres.order('created_at ASC').each do |ent|
        @json << {
          enterprise: ent.enterprise.name,
          inactive: ent.inactive,
          inactive_date: ent.inactive_date.present? ? ent.inactive_date : 'empty' ,
          source_list: ent.source_list,
          zone: ent.zone
        }
      end

      render json: @json
    end


    def detail
      @candidate = Candidate::Cadastre.by_cpf(params[:candidate_id]).first
      @positions = @candidate.positions.where(program_id: params[:program_id]).map do |key|
        [key.position, [key.created_at.year, key.created_at.month, key.created_at.day]]
      end

      respond_to do |format|
        format.json { render json: @positions}
        format.html { @candidate }
        format.js {

          date = Date.parse(params[:date]) rescue nil
          @day = Candidate::DayOcurrency.find_by_date_ocurrency(date) rescue nil

          if @day.present?
            @events    = {
                update_incomes: @day.update_income,
                update_dependents: @day.update_dependent,
                update_special_conditions: @day.update_special_condition,
                update_old: @day.update_old,
                halted: @day.halted,
                update_arrival_df: @day.update_arrival_df,
                enables_day: @day.enables_day,
                change_zone: @day.change_zone,
                update_data: @day.update_data,
                contemplateds_day: @day.contemplated_day
              }
          else
            @events = {}
          end
        }
      end
    end

    def enterprise_cadastre_situation
      @enterprise_cadastre_situation = Candidate::EnterpriseCadastreSituation.where(enterprise_cadastre_id:params[:id])
    end

    def update_positions
      @day      = params[:by_date].present? ? params[:by_date] : Date.today.strftime('%d/%m/%Y')
      @zone     = params[:by_zone].present? ? params[:by_zone] : 1
      @program  = params[:by_program].present? ? params[:by_program] : 1

      @positions = Candidate::Position.update_by_day(@day, @zone, @program, params[:page])
    end

    def programs
      render json: ['RII', 'RIE', 'DEFICIÊNTES', 'VULNERÁVEL', 'IDOSOS']
    end

    private

    def add_cors_headers
      origin = request.headers["Origin"]
      unless (not origin.nil?) and (origin == "http://localhost" or origin.starts_with? "http://localhost:")
        origin = "http://www.codhab.df.gov.br/"
      end
      headers['Access-Control-Allow-Origin'] = origin
      headers['Access-Control-Allow-Methods'] = 'POST, GET'
      allow_headers = request.headers["Access-Control-Request-Headers"]
      if allow_headers.nil?
        #shouldn't happen, but better be safe
        allow_headers = 'Origin, Authorization, Accept, Content-Type'
      end
      headers['Access-Control-Allow-Headers'] = allow_headers
      headers['Access-Control-Allow-Credentials'] = 'true'
      headers['Access-Control-Max-Age'] = '1728000'
    end

    def set_params_find
      params.require(:find).permit(:cpf)
    end

    def set_headers
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Request-Method'] = '*'
    end

  end
end

components/habitation_portal/app/controllers/habitation_portal/lists_controller.rb
require_dependency 'habitation_portal/application_controller'

module HabitationPortal
  class ListsController < ApplicationController
    before_action :set_list, only: [:show]

    has_scope :cpf
    has_scope :by_name

    def index
      @lists = ::Candidate::List.all.order(:title)
    end

    def show
      @geral = "#{@list.view_target}".constantize.where("#{@list.condition_sql}")
      @candidates = apply_scopes(@geral).paginate(:page => params[:page], :per_page => 100)
    end

    private

    def set_list
      begin
        @list = ::Candidate::List.portal.friendly.find(params[:id])
      rescue
        redirect_to '/404'
      end
    end
  end
end

components/habitation_portal/app/helpers/habitation_portal/application_helper.rb
module HabitationPortal
  module ApplicationHelper

    def translate_list(list)
      case list
      when 'rii'
        "RII"
      when 'rie'
        "RIE"
      when 'older'
        "IDOSOS"
      when 'vulnerable'
        "VULNERÁVEL"
      when 'special'
        "PESSOAS COM DEFICIÊNCIA"
      end

    end

    def program(id)
      case id
      when 1
        'RII'
      when 2
        'RIE'
      when 4
        'VULNERÁVEL'
      end
    end

    def cpf_mask(cpfs)
        cpf1 = cpfs
        cpf = cpf1[6, 3]
        cpf2 = cpf1[9, 2]
        cpf = "XXX.XXX.#{cpf}-#{cpf2}"
   end


  end
end

components/habitation_portal/app/views/habitation_portal/lists/index.html.haml
/ conteudo da pagina
.container
  .row
    .col-md-12.box
      .box_internal
        .row
          .col-md-12
            .container
              %h1 
                %b Listas Habitação
               
        .row
          .col-md-12
            .container
              
        .row
          .col-md-12
            %table#data-table-command.table.table-striped.table-vmiddle.datatable
              %thead
                %tr
                  %th Nome
                  %th Link
              %tbody
                - @lists.each do |list|
                  %tr
                    %td= list.title
                    %td= link_to "Acessar", list_path(list)

components/habitation_portal/app/views/habitation_portal/lists/show.html.haml
/ conteudo da pagina
.container
  .row
    .col-md-12.box
      .box_internal
        .row
          .col-md-12
            .container
              %h1
                %b= @list.title
        .row
          .col-md-12
            .container
              = @list.description.to_s.html_safe
        %hr/
        .row
          .container
            - if @list.cpf_filter
              .col-md-6
                = simple_form_for url_for, method: :get do |f|
                  .row
                    - if @list.name_filter
                      .col-md-5
                        = f.label "Nome", class: 'fg-label'
                        = f.input :by_name, label: false, input_html: { name:  'by_name', value: params[:by_name]}
                    .col-md-5
                      = f.input :cpf, input_html: { name:  'cpf', value: params[:cpf]}
                    .col-md-2{style: 'padding-top: 27px'}
                      = f.submit 'Pesquisar', name: nil, class: 'btn btn-success', data: {  disable_with: "Pesquisando aguarde..."}
            .col-md-3
            .col-md-3
              %br/
              %br/
              %h4
                %b Total da lista: #{number_with_delimiter(@geral.count, delimiter: ".")}
        .row
          .col-md-12
            - if @candidates.present?
              %table#data-table-command.table.table-striped.table-vmiddle.datatable
                %thead
                  %tr
                    %th Posição
                    %th Nome
                    %th CPF
                    %th Pontuação
                    - if @candidates.first.program_id == 2
                      %th Sigla
                    %th Situação
                %tbody
                  - @candidates.each do |candidate|
                    %tr
                      %td.col-md-1= @geral.map(&:cpf).find_index(candidate.cpf) + 1
                      %td= link_to candidate.name, candidate_path(candidate.id), data: {disable_with: "Carregando aguarde..."}
                      %td= candidate.cpf.format_obfuscator_cpf
                      %td= candidate.total
                      - if @candidates.first.program_id == 2
                        %td= candidate.fantasy_name
                      %td
                        %span.label.label-success
                          - if candidate.cadastre.enterprise_cadastres.present?
                            - if candidate.cadastre.enterprise_cadastres.last.inactive == true
                              = "#{candidate.cadastre.current_situation_name} - #{candidate.cadastre.enterprise_cadastres.where(inactive: true).count}º RECUSA - #{candidate.cadastre.enterprise_cadastres.last.enterprise.name}"
                            - elsif candidate.cadastre.enterprise_cadastres.nil?
                              = "#{candidate.cadastre.current_situation_name}"
                            - else
                              = "#{candidate.cadastre.current_situation_name} - INDICADO - #{candidate.cadastre.enterprise_cadastres.last.enterprise.name}"
                          - else
                            = "#{candidate.cadastre.current_situation_name}"
            - else
              %b Sem resultado para consulta.
        .row
          .col-md-6.col-md-offset-3
            .container
              = will_paginate @candidates, renderer: BootstrapPagination::Rails